export const ErrorCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TODO_NOT_FOUND: "TODO_NOT_FOUND",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TODO_ACTIVITY_NOT_FOUND: "TODO_ACTIVITY_NOT_FOUND",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  UNAUTHORIZED_ACTIVITY_DELETION: "UNAUTHORIZED_ACTIVITY_DELETION",
  TAG_NAME_EXISTS: "TAG_NAME_EXISTS",
  PROJECT_NAME_EXISTS: "PROJECT_NAME_EXISTS",
  DEPENDENCY_EXISTS: "DEPENDENCY_EXISTS",
  DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",
  SELF_DEPENDENCY: "SELF_DEPENDENCY",
  DEPENDENCY_CYCLE: "DEPENDENCY_CYCLE",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorResponse {
  code: ErrorCode;
  message: string;
  issues?: unknown[];
}
